<?xml version='1.0' encoding='UTF-8'?>
<Tag plugin="workflow-support@2.20">
  <node class="cps.n.StepEndNode" plugin="workflow-cps@2.54">
    <parentIds>
      <string>18</string>
    </parentIds>
    <id>19</id>
    <startId>5</startId>
  </node>
  <actions>
    <wf.a.BodyInvocationAction plugin="workflow-api@2.27"/>
    <wf.a.TimingAction plugin="workflow-api@2.27">
      <startTime>1533883708121</startTime>
    </wf.a.TimingAction>
    <wf.a.ErrorAction plugin="workflow-api@2.27">
      <error class="hudson.AbortException">
        <detailMessage>script returned exit code 1</detailMessage>
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:335)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:289)</trace>
          <trace>java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)</trace>
          <trace>java.util.concurrent.FutureTask.run(Unknown Source)</trace>
          <trace>java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)</trace>
          <trace>java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)</trace>
          <trace>java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)</trace>
          <trace>java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)</trace>
          <trace>java.lang.Thread.run(Unknown Source)</trace>
        </stackTrace>
        <suppressedExceptions class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
          <c class="list"/>
          <list reference="../c"/>
        </suppressedExceptions>
      </error>
    </wf.a.ErrorAction>
    <wf.a.TimingAction plugin="workflow-api@2.27">
      <startTime>1533883708132</startTime>
    </wf.a.TimingAction>
  </actions>
</Tag>